config/routes.rb
TaskQueue::Application.routes.draw do
  devise_for :users do
    get "signin", :to => "devise/sessions#new"
  end

  resources :tasks do
    get :complete, :on => :member
    get :incomplete, :on => :member
    get :prioritize, :on => :member
    get :deprioritize, :on => :member
    get :time, :on => :collection
    post :time, :on => :collection
    get :category, :on => :collection
    post :category, :on => :collection
    get :timecat, :on => :collection
    post :timecat, :on => :collection
  end

  get "home/index"

  
  

  root :to => 'tasks#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  def self.names
    category = []
    Category.all.each do |x|
      category << [x.name, x.id]
    end
    return category
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :category
  belongs_to :user
  
  def resume
    update_attribute(:completed, false)
  end
  
  def finish
    update_attribute(:completed, true)
  end
  
  def move_up
    decrement!(:priority, by = 1)
    Task.find_each do |other_task|
      if other_task.priority == self.priority && other_task.id != self.id
        other_task.increment!(:priority, by = 1)
      end
    end
  end
  
  def move_down
    increment!(:priority, by = 1)
    Task.find_each do |other_task|
      if other_task.priority == self.priority && other_task.id != self.id
        other_task.decrement!(:priority, by = 1)
      end
    end
  end
  
  def self.by_priority
    find(:all, :order => :priority)
  end
  
  def self.organize_by_time(time)
    where(:time => time)
  end
  
  def self.organize_by_category(category_id)
    where(:category_id => category_id)
  end
  
  def self.get_tasks_for_user(task)
    where(:user_id => task).by_priority
  end
end

app/models/time_interval.rb
class TimeInterval
  def self.all
    [5, 15, 30, 60]
  end
  
  def self.form_parameters
    all.inject([]) do |parameters, interval|
      parameters << ["#{interval} min", interval]
    end
  end
end
  

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  has_many :tasks
  
  validates :email, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/signins_controller.rb
class SigninsController < ApplicationController
  def index
  end
  
  def show
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_filter :find_task, :only => [:show, :edit, :update, :destroy, :complete, :incomplete]
  
  def index
    if current_user != nil
      @tasks = current_user.tasks.by_priority
    else
      redirect_to new_user_session_path
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task])
    @task.user_id = current_user.id
    @task.category_id = 1
    if @task.save
      redirect_to tasks_path, :notice => 'Task was successfully created.'
    else
      render :action => "new"
    end
  end

  def update
    if @task.update_attributes(params[:task])
      redirect_to @task, :notice => 'Task was successfully updated.'
    else
      render :action => "edit"
    end
  end
  
  def show
    if @task.user_id == current_user.id
      render "show"
    else
      render "error"
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_url
  end
  
  def complete
    @task.finish
    redirect_to tasks_path, :notice => "Task was completed"
  end
  
  def incomplete
    @task.resume
    redirect_to tasks_path, :notice => "Task has been re-opened"
  end
  
  def prioritize
    find_task
    @task.move_up
    redirect_to tasks_path, :notice => "Task has moved up in priority"
  end
  
  def deprioritize
    find_task
    @task.move_down
    redirect_to tasks_path, :notice => "Task has moved down in priority"
  end
  
  def time
    @tasks = current_user.tasks.organize_by_time(params[:free_time])
    render :template => 'tasks/time'
  end
  
  def category
    @tasks = current_user.tasks.organize_by_category(params[:category])
    render :template => "tasks/category"
  end
  
  def user_tasks
    get_tasks_for_user(current_user.id)
  end
  
  def timecat
    @tasks = current_user.tasks.organize_by_category(params[:category]).organize_by_time(params[:free_time])
    render :template => "tasks/timecat"
  end

private
  
  def find_task
    @task = Task.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def index
  end
  
  def show
    @user = User.find(params[:id])
  end

  def new
    @title = "Sign up"
  end
  
  def signin
    redirect_to signin_user_path, :action => "signin"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_header.html.erb
<header>
	<div id="header_content">
		<h1 id="logo">Task Queue</h1>
		<hgroup>
		<% if signed_in? %>
			<h2>You are signed in.</h2>
			<h3><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></h3>
		<% else %>
			<h1><%= link_to 'Sign in', signin_path %></h1>
		<% end %>
		<hgroup>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskQueue</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery" %>
  <%= javascript_include_tag "taskqueue" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header'%>

	<%= yield %>

</body>
</html>

app/views/signin/index.html.erb
<h1>Yay! It's a signin page that doesn't do anything!</h1>

app/views/tasks/_completed.html.erb
<% @tasks.each do |task| %>
	<% if task.completed? %>
	<li>
		<p class="button input"><%= link_to 'reopen', incomplete_task_path(task) %></p>
		<h2><%= task.task %></h2>
		<p class="button input delete"><%= link_to 'delete', task_path(task), :confirm => 'Are you sure?', :method => :delete %></p>
	</li>
	<% else %>
	<% end %>
<% end %>

app/views/tasks/_filter.html.erb
<section id="filter">
	<%= form_tag(timecat_tasks_path) do %>
	  <div class="field">
		<%= label_tag("Time: ") %>
		<%= select_tag(:free_time, options_for_select(TimeInterval.form_parameters)) %>
	    <%= label_tag("Category: ") %>
		<%= select_tag(:category, options_for_select(Category.names)) %>
		<%= submit_tag("Go") %>
	  </div>
	<% end %>
	<p class="input button"><%= link_to 'new task', new_task_path %></p>
</section>

app/views/tasks/_form.html.erb
<div id="main">
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<div class="clear"></div>
	<section id="edit">

<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<ul id="tasks">
	<li>
		<p class="checkbox input"><%= link_to '' %></p>
   		<p class="title"><%= f.text_field :task, :value => "Task Title", :class => "input" %></p>

		<div class="details">
			<p class="time"><%= f.select(:time, options_for_select(TimeInterval.form_parameters)) %></p>
		    <p class="category"><%= f.collection_select(:category_id, Category.all, :id, :name) %></p>
		</div>
		<div class="more">
		    <p><%= f.text_area :description, :value => "Task Description", :class => "description input" %></p>
			<div class="controls">
				<p><%= f.submit "save task", :class => "input button" %></p>
			</div>
		</div>
		<% end %>
	</li>
</ul>

</section>
</div>

app/views/tasks/_not_completed.html.erb
<% @tasks.each do |task| %>
<% if !task.completed? %>
  <li>
	<%= link_to '', complete_task_path(task), :class  => "checkbox input" %>

   	<h2><a href="#"><%= "#{task.task}" %></a></h2>
	<div class="details">
    	<p class="time"><%= task.time %> min</p>
		<p class="category"><%= task.category.name %></p>
		<p><%= link_to image_tag('prioritize.png'), prioritize_task_path(task) %></p>
		<p><%= link_to image_tag('deprioritize.png'), deprioritize_task_path(task) %></p>
	</div>
	<div class="more_info">
		<p class="description input"><%= task.description %></p>
		<div class="controls">
			<p class="button input"><%= link_to 'edit task', edit_task_path(task) %></p>
			<p class="button input"><%= link_to 'delete', task_path(task), :confirm => 'Are you sure?', :method => :delete %></p>
		</div>
	</div>
  </li>
<% else %>
<% end %>
<% end %>

app/views/tasks/category.html.erb
<h1><%= "#{Category.find(params[:category]).name}" %> tasks.</h1>

<% if @tasks.empty? %>
	<p>No tasks for this category</p>
<% else %>
	<%= render 'not_completed' %>
<% end %>

app/views/tasks/edit.html.erb
<div id="main">
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= render 'form' %>
	<div class="clear"></div>
	<%= link_to 'Show', @task %> |
	<%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/error.html.erb
<h1>This ain't your task!</h1>

app/views/tasks/index.html.erb
<div id="main">
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= render 'filter' %>
	<div class="clear"></div>

	<section id="all_tasks">
		<div id="incomplete">
			<h1>Current Tasks</h1>
			<ul id="tasks">
				<%= render 'not_completed'%>
			</ul>
		</div>
		
		<div id="complete">
			<h1>Completed Tasks</h1>
			<ul id="tasks">
				<%= render 'completed'%>
			</ul>
		</div>
		<div class="clear"></div>
	</section>
</div>

app/views/tasks/new.html.erb
<div id="main">
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<%= render 'form' %>
	<div class="clear"></div>
	<%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Task:</b>
  <%= @task.task %>
</p>

<p>
  <b>Time:</b>
  <%= @task.time %> minutes
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Category:</b>
  <%= @task.category %>
  
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/time.html.erb
<h1>Tasks that take <%= "#{params[:free_time]} minutes" %>.</h1>

<%= p @tasks.inspect %>

<% if @tasks == nil %>
	<p>No tasks for this time category</p>
<% else %>
	<%= render 'not_completed' %>
<% end %>

app/views/tasks/timecat.html.erb
<h1><%= "#{Category.find(params[:category]).name}" %> tasks that take <%= "#{params[:free_time]} minutes" %>.</h1>

<% if @tasks.empty? %>
	<p>No tasks for this category</p>
<% else %>
	<%= render 'not_completed' %>
<% end %>

app/views/user/tasks.html.erb
<h1>User filtering should work</h1>